<?php
use \Drupal\Core\Url;

function form_example_page_attachments(array &$page) {
 $page['#attached']['library'][] = 'form_example/form_example'; // modulename/libraryname
 $page['#attached']['drupalSettings']['custom_variable'] = "aleart system";
}

/**
* Implements hook_preprocess_page(&$variables)
*/
function theme_name_preprocess_page(&$variables) {
    if (\Drupal::service('path.matcher')->isFrontPage() == 1) {
      $variables['#attached']['library'][] = 'theme_name/slick';
    }
  }